### ISSUE TITLE
重新 Create Activity 以后 Scroll ListView 时会 crash

### ISSUE THREAD

**Issue by 109021017** [109021017/AppManager#2]
## 重新 Create Activity 以后 Scroll ListView Crash

java.lang.IllegalStateException: Content view not yet created
    at android.app.ListFragment.ensureList(ListFragment.java:386)
    at android.app.ListFragment.getListView(ListFragment.java:280)
    at com.willme.appmanager.MainActivity.getCurrentList(MainActivity.java:173)
    at com.willme.appmanager.MainActivity.access$000(MainActivity.java:38)
    at com.willme.appmanager.MainActivity$1.onPanelFlingReachesEdge(MainActivity.java:66)
    at com.android.dialer.widget.OverlappingPaneLayout$DragHelperCallback.onViewDragStateChanged(OverlappingPaneLayout.java:1033)
    at com.android.dialer.widget.ViewDragHelper.setDragState(ViewDragHelper.java:934)
    at com.android.dialer.widget.ViewDragHelper.continueSettling(ViewDragHelper.java:790)
    at com.android.dialer.widget.OverlappingPaneLayout.computeScroll(OverlappingPaneLayout.java:854)

**Comment by 109021017** [comment]
Fixed by 7b6c816
